/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as HomepageManagementRouteImport } from './routes/homepage-management'
import { Route as BooksManagementRouteImport } from './routes/books-management'
import { Route as AddBooksRouteImport } from './routes/add-books'
import { Route as IndexRouteImport } from './routes/index'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageManagementRoute = HomepageManagementRouteImport.update({
  id: '/homepage-management',
  path: '/homepage-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksManagementRoute = BooksManagementRouteImport.update({
  id: '/books-management',
  path: '/books-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBooksRoute = AddBooksRouteImport.update({
  id: '/add-books',
  path: '/add-books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-books': typeof AddBooksRoute
  '/books-management': typeof BooksManagementRoute
  '/homepage-management': typeof HomepageManagementRoute
  '/orders': typeof OrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-books': typeof AddBooksRoute
  '/books-management': typeof BooksManagementRoute
  '/homepage-management': typeof HomepageManagementRoute
  '/orders': typeof OrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-books': typeof AddBooksRoute
  '/books-management': typeof BooksManagementRoute
  '/homepage-management': typeof HomepageManagementRoute
  '/orders': typeof OrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-books'
    | '/books-management'
    | '/homepage-management'
    | '/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-books'
    | '/books-management'
    | '/homepage-management'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/add-books'
    | '/books-management'
    | '/homepage-management'
    | '/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBooksRoute: typeof AddBooksRoute
  BooksManagementRoute: typeof BooksManagementRoute
  HomepageManagementRoute: typeof HomepageManagementRoute
  OrdersRoute: typeof OrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage-management': {
      id: '/homepage-management'
      path: '/homepage-management'
      fullPath: '/homepage-management'
      preLoaderRoute: typeof HomepageManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books-management': {
      id: '/books-management'
      path: '/books-management'
      fullPath: '/books-management'
      preLoaderRoute: typeof BooksManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-books': {
      id: '/add-books'
      path: '/add-books'
      fullPath: '/add-books'
      preLoaderRoute: typeof AddBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBooksRoute: AddBooksRoute,
  BooksManagementRoute: BooksManagementRoute,
  HomepageManagementRoute: HomepageManagementRoute,
  OrdersRoute: OrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
