/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ManageHomepageRouteImport } from './routes/manage-homepage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomepageManagementRouteImport } from './routes/homepage-management'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as ContactManagementRouteImport } from './routes/contact-management'
import { Route as ClientManagementRouteImport } from './routes/client-management'
import { Route as CategoryManagementRouteImport } from './routes/category-management'
import { Route as BooksManagementRouteImport } from './routes/books-management'
import { Route as AddBooksRouteImport } from './routes/add-books'
import { Route as IndexRouteImport } from './routes/index'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageHomepageRoute = ManageHomepageRouteImport.update({
  id: '/manage-homepage',
  path: '/manage-homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageManagementRoute = HomepageManagementRouteImport.update({
  id: '/homepage-management',
  path: '/homepage-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactManagementRoute = ContactManagementRouteImport.update({
  id: '/contact-management',
  path: '/contact-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientManagementRoute = ClientManagementRouteImport.update({
  id: '/client-management',
  path: '/client-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryManagementRoute = CategoryManagementRouteImport.update({
  id: '/category-management',
  path: '/category-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksManagementRoute = BooksManagementRouteImport.update({
  id: '/books-management',
  path: '/books-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBooksRoute = AddBooksRouteImport.update({
  id: '/add-books',
  path: '/add-books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-books': typeof AddBooksRoute
  '/books-management': typeof BooksManagementRoute
  '/category-management': typeof CategoryManagementRoute
  '/client-management': typeof ClientManagementRoute
  '/contact-management': typeof ContactManagementRoute
  '/discounts': typeof DiscountsRoute
  '/homepage-management': typeof HomepageManagementRoute
  '/login': typeof LoginRoute
  '/manage-homepage': typeof ManageHomepageRoute
  '/orders': typeof OrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-books': typeof AddBooksRoute
  '/books-management': typeof BooksManagementRoute
  '/category-management': typeof CategoryManagementRoute
  '/client-management': typeof ClientManagementRoute
  '/contact-management': typeof ContactManagementRoute
  '/discounts': typeof DiscountsRoute
  '/homepage-management': typeof HomepageManagementRoute
  '/login': typeof LoginRoute
  '/manage-homepage': typeof ManageHomepageRoute
  '/orders': typeof OrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-books': typeof AddBooksRoute
  '/books-management': typeof BooksManagementRoute
  '/category-management': typeof CategoryManagementRoute
  '/client-management': typeof ClientManagementRoute
  '/contact-management': typeof ContactManagementRoute
  '/discounts': typeof DiscountsRoute
  '/homepage-management': typeof HomepageManagementRoute
  '/login': typeof LoginRoute
  '/manage-homepage': typeof ManageHomepageRoute
  '/orders': typeof OrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-books'
    | '/books-management'
    | '/category-management'
    | '/client-management'
    | '/contact-management'
    | '/discounts'
    | '/homepage-management'
    | '/login'
    | '/manage-homepage'
    | '/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-books'
    | '/books-management'
    | '/category-management'
    | '/client-management'
    | '/contact-management'
    | '/discounts'
    | '/homepage-management'
    | '/login'
    | '/manage-homepage'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/add-books'
    | '/books-management'
    | '/category-management'
    | '/client-management'
    | '/contact-management'
    | '/discounts'
    | '/homepage-management'
    | '/login'
    | '/manage-homepage'
    | '/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBooksRoute: typeof AddBooksRoute
  BooksManagementRoute: typeof BooksManagementRoute
  CategoryManagementRoute: typeof CategoryManagementRoute
  ClientManagementRoute: typeof ClientManagementRoute
  ContactManagementRoute: typeof ContactManagementRoute
  DiscountsRoute: typeof DiscountsRoute
  HomepageManagementRoute: typeof HomepageManagementRoute
  LoginRoute: typeof LoginRoute
  ManageHomepageRoute: typeof ManageHomepageRoute
  OrdersRoute: typeof OrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-homepage': {
      id: '/manage-homepage'
      path: '/manage-homepage'
      fullPath: '/manage-homepage'
      preLoaderRoute: typeof ManageHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage-management': {
      id: '/homepage-management'
      path: '/homepage-management'
      fullPath: '/homepage-management'
      preLoaderRoute: typeof HomepageManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-management': {
      id: '/contact-management'
      path: '/contact-management'
      fullPath: '/contact-management'
      preLoaderRoute: typeof ContactManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-management': {
      id: '/client-management'
      path: '/client-management'
      fullPath: '/client-management'
      preLoaderRoute: typeof ClientManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-management': {
      id: '/category-management'
      path: '/category-management'
      fullPath: '/category-management'
      preLoaderRoute: typeof CategoryManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books-management': {
      id: '/books-management'
      path: '/books-management'
      fullPath: '/books-management'
      preLoaderRoute: typeof BooksManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-books': {
      id: '/add-books'
      path: '/add-books'
      fullPath: '/add-books'
      preLoaderRoute: typeof AddBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBooksRoute: AddBooksRoute,
  BooksManagementRoute: BooksManagementRoute,
  CategoryManagementRoute: CategoryManagementRoute,
  ClientManagementRoute: ClientManagementRoute,
  ContactManagementRoute: ContactManagementRoute,
  DiscountsRoute: DiscountsRoute,
  HomepageManagementRoute: HomepageManagementRoute,
  LoginRoute: LoginRoute,
  ManageHomepageRoute: ManageHomepageRoute,
  OrdersRoute: OrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
